# Generated by Django 5.2.15 on 2026-07-08 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, default='')),
                ('payment_source', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('Cash', 'Cash'), ('Brokerage', 'Brokerage'), ('UPI', 'UPI'), ('Other', 'Other')], default='Bank Transfer', max_length=20)),
                ('income_date', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-income_date'],
                'indexes': [models.Index(fields=['-income_date'], name='api_income_income__c24524_idx'), models.Index(fields=['source', '-income_date'], name='api_income_source_283e2d_idx')],
            },
        ),
    ]
