# Generated by Django 6.0.5 on 2026-07-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_income'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='income',
            name='api_income_income__c24524_idx',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='api_income_source_283e2d_idx',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
