# Generated by Django 5.2.15 on 2026-07-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_income_api_income_income__c24524_idx_and_more'),
        ('api', '0011_chat_message'),
    ]

    operations = [
    ]
