# Generated by Django 5.2.15 on 2026-07-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
