# Generated by Django 6.0.5 on 2026-07-11 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_recurringexpense_expense_recurring_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
