# Generated by Django 5.2.16 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_devicetoken_notificationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recurring_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
    ]
