# Generated by Django 5.2.16 on 2026-07-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_expense_recurring_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='recurring_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
